name: flutter_google_places_sdk
description: A Flutter plugin for google places sdk that uses the native libraries on each platform
version: 0.4.2+1
homepage: https://github.com/matanshukry/flutter_google_places_sdk/tree/master/flutter_google_places_sdk

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_google_places_sdk_platform_interface: ^0.3.2+1
  flutter_google_places_sdk_ios:
    git:
      url: https://github.com/mustafaezzeldin2020/flutter_google_places_sdk.git
      ref: main
      path: flutter_google_places_sdk_ios
  flutter_google_places_sdk_web: ^0.2.0
  flutter_google_places_sdk_android:
    git:
      url: https://github.com/mustafaezzeldin2020/flutter_google_places_sdk.git
      ref: main
      path: flutter_google_places_sdk_android
  flutter_google_places_sdk_windows: ^0.2.1
  flutter_google_places_sdk_linux: ^0.2.1
  flutter_google_places_sdk_macos: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_google_places_sdk_android
      ios:
        default_package: flutter_google_places_sdk_ios
      web:
        default_package: flutter_google_places_sdk_web
      windows:
        default_package: flutter_google_places_sdk_windows
      linux:
        default_package: flutter_google_places_sdk_linux
      macos:
        default_package: flutter_google_places_sdk_macos
